Repository MalteMagnussen/CA2, pull requests merged in 2019-10, with the labels that each got.

#13 Issue#3 entity person
  src/main/java/entities/Person.java
Labels: enhancement

#14 Issue#4 entity hobby
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
  src/main/resources/META-INF/persistence.xml
Labels: enhancement

#15 Named Queries for Person and Hobby
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
Labels: enhancement

#12 Scrum Plan HTML Page
  src/main/webapp/css/css.css
  src/main/webapp/scrum.html
Labels: enhancement

#18 Initial API documentation.
  src/main/java/dto/HobbyDTO_IN.java
  src/main/java/dto/HobbyDTO_OUT.java
  src/main/java/dto/MovieInfo.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/ResourceExample.java
  src/main/java/rest/SearchResource.java
  src/main/webapp/openapi/index.html
  src/main/webapp/resources/domainmodel.png
Labels: Sprint 1, documentation

#16 Travis Deployment Fix
  .travis.yml
Labels: Sprint 1, bug

#19 Initial facade methods incl tests
  pom.xml
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/resources/META-INF/persistence.xml
  src/test/java/facades/FacadeExampleTest.java
  src/test/java/facades/SearchFacadeTest.java
Labels: Sprint 1

#22 Updated index.html with navbar and proper links etc.
  src/main/webapp/META-INF/context.xml
  src/main/webapp/css/css.css
  src/main/webapp/index.html
Labels: Sprint 1

#23 Integrated facademethods into REST
  src/main/java/entities/Person.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacadeTest.java
Labels: Sprint 1

#27 Issue#21 rest test
  src/main/java/dto/HobbyDTO_IN.java
  src/main/java/dto/HobbyDTO_OUT.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacadeTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 2

#28 Clean Up and CORS
  src/main/java/cors/CorsRequestFilter.java
  src/main/java/cors/CorsResponseFilter.java
  src/main/java/dto/HobbyDTO_IN.java
  src/main/java/dto/HobbyDTO_OUT.java
  src/main/java/dto/MovieInfo.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
  src/main/java/entities/RenameMe.java
  src/main/java/errorhandling/ExceptionDTO.java
  src/main/java/facades/FacadeExample.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/SearchResource.java
  src/main/java/utils/EMF_Creator.java
  src/main/java/utils/Settings.java
  src/main/webapp/scrum.html
  src/test/java/facades/FacadeExampleTest.java
  src/test/java/facades/SearchFacadeTest.java
  src/test/java/rest/RenameMeResourceTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 1

#32 Phone Entity + Hopefully the right relation.
  src/main/java/entities/Person.java
  src/main/java/entities/Phone.java
  src/main/resources/META-INF/persistence.xml
Labels: Sprint 2

#33 Creation of remaining entities
  src/main/java/entities/Address.java
  src/main/java/entities/CityInfo.java
  src/main/java/entities/Person.java
Labels: Sprint 2

#37 Update of DTO + some refactoring
  src/main/java/dto/AddressDTO_IN.java
  src/main/java/dto/AddressDTO_OUT.java
  src/main/java/dto/CityInfoDTO_IN.java
  src/main/java/dto/CityInfoDTO_OUT.java
  src/main/java/dto/HobbyDTO_IN.java
  src/main/java/dto/HobbyDTO_OUT.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/dto/PhoneDTO_IN.java
  src/main/java/dto/PhoneDTO_OUT.java
  src/main/java/entities/Address.java
  src/main/java/entities/CityInfo.java
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
  src/main/java/entities/Phone.java
  src/main/java/facades/SearchFacade_Impl.java
Labels: Sprint 2

#38 New Facade Methods and JavaDoc on Facade Interface
  src/main/java/dto/CityInfoDTO_OUT.java
  src/main/java/entities/CityInfo.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
Labels: Sprint 2

#39 Issue#34 update dto version 2.0
  src/main/java/dto/AddressDTO_IN.java
  src/main/java/dto/AddressDTO_OUT.java
  src/main/java/dto/CityInfoDTO_IN.java
  src/main/java/dto/CityInfoDTO_OUT.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/dto/PhoneDTO_IN.java
  src/main/java/dto/PhoneDTO_OUT.java
  src/main/java/entities/Person.java
Labels: Sprint 2

#41 Issue#21 rest test
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/entities/Address.java
  src/main/java/entities/CityInfo.java
  src/main/java/entities/Person.java
  src/main/java/entities/Phone.java
  src/main/java/utils/EMF_Creator.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 2

#43 Droplet Fix
  src/main/resources/config.properties
Labels: Sprint 2, bug

#42 Update REST, API-doc for review
  src/main/java/dto/CityInfoDTO_OUT.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/rest/SearchResource.java
Labels: Sprint 2, documentation

#46 Issue#21 rest test
  pom.xml
  src/main/java/dto/AddressDTO_IN.java
  src/main/java/dto/CityInfoDTO_IN.java
  src/main/java/dto/HobbyDTO_IN.java
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/dto/PhoneDTO_IN.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacadeTest.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#48 fix of database scripts
  SQL-Scripts/CA2 DDL Forward-Engineered.sql
  SQL-Scripts/CA2 DML.sql
  SQL-Scripts/CA2 DatabaseModel.PNG
Labels: Sprint 2

#49 New Facade Methods and refactoring
  src/main/java/dto/AddressDTO_OUT.java
  src/main/java/dto/CityInfoDTO_OUT.java
  src/main/java/dto/HobbyDTO_OUT.java
  src/main/java/dto/PersonDTO_OUT.java
  src/main/java/dto/PhoneDTO_OUT.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacadeTest.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#52 Even more facade testing
  src/main/java/dto/PhoneDTO_IN.java
  src/main/java/entities/Person.java
  src/main/java/facades/SearchFacade_Impl.java
  src/test/java/facades/SearchFacadeTest.java
  src/test/java/facades/SearchFacade_ImplTest.java
Labels: Sprint 2

#56 Changed path and method name
  src/main/java/rest/SearchResource.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#53 Update REST-endpoints and their tests
  src/main/java/dto/AddressDTO_OUT.java
  src/main/java/dto/CityInfoDTO_IN.java
  src/main/java/dto/PhoneDTO_OUT.java
  src/main/java/entities/Person.java
  src/main/java/entities/Phone.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 2

#54 Refactoring Add and Edit Person.
  src/main/java/entities/Address.java
  src/main/java/entities/CityInfo.java
  src/main/java/entities/Hobby.java
  src/main/java/entities/Phone.java
  src/main/java/facades/SearchFacade_Impl.java
  src/test/java/facades/SearchFacade_ImplTest.java
Labels: Sprint 3, bug

#58 Issue#57 refactor rest test create all
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#61 Added getHobbyByName method
  src/main/java/entities/Hobby.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#64 Implement REST for edit- & deletePerson
  src/main/java/dto/PersonDTO_IN.java
  src/main/java/entities/Address.java
  src/main/java/entities/CityInfo.java
  src/main/java/entities/Hobby.java
  src/main/java/entities/Person.java
  src/main/java/entities/Phone.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#66 Issue#65 more rest testing
  src/main/java/facades/SearchFacade_Impl.java
  src/test/java/rest/SearchResourceTest.java
Labels: Sprint 3

#69 Issue#67 fix create all endpoint
  src/main/java/entities/Address.java
  src/main/java/facades/SearchFacade_Impl.java
  src/test/java/facades/SearchFacade_ImplTest.java
Labels: Sprint 3

#71 Implemented editHobby with endpoint, facade, tests and all
  src/main/java/entities/Hobby.java
  src/main/java/facades/ISearchFacade.java
  src/main/java/facades/SearchFacade_Impl.java
  src/main/java/rest/SearchResource.java
  src/test/java/facades/SearchFacade_ImplTest.java
  src/test/java/rest/SearchResourceTest.java
Labels: DONT MERGE YET, Sprint 3

#70 Update README.md
  README.md
Labels: Sprint 3, documentation
